link:
  forward: TIO_000138
  reverse: TIO_000139
  file: sample.tsv
update:
  frequency: Monthly
  method: awk -F '\t' 'FNR==1{fn++}fn==1{mi_id[$1]=$2}fn==2{mimat_id[$1]=$4}fn==3&&$1{print mi_id[$1] "\t" mimat_id[$2]}' $TOGOID_ROOT/input/mirbase/mirna.tsv $TOGOID_ROOT/input/mirbase/mirna_mature.tsv $TOGOID_ROOT/input/mirbase/mirna_pre_mature.tsv
