link:
  forward: TIO_000010
  reverse: TIO_000011
  file: sample.tsv
update:
  frequency: Monthly
  method: awk -v prefix="MedGen:" -f $TOGOID_ROOT/bin/parse_vcv_phenotype.awk $TOGOID_ROOT/input/clinvar/variant_summary.txt
