link:
  forward: TIO_000136
  reverse: TIO_000137
  file: sample.tsv
update:
  frequency: Weekly
  method: awk -F '\t' -v db=RFAM '$2==db{print $1 "_" $4 "\t" $3}' $TOGOID_ROOT/input/rnacentral/id_mapping.tsv
