link:
  forward: TIO_000035
  reverse: TIO_000034
  file: sample.tsv
update:
  frequency: Bimonthly
  method: awk -F "\t" 'FNR>=2&&$33{gsub("\"","",$33); split($33,a,"|"); for(k in a)print substr($1,6) "\t" a[k]}' $TOGOID_ROOT/input/hgnc/hgnc_complete_set.tsv
