# pubchem_pathway-uniprot
PREFIX bp: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT (COUNT(*) AS ?total)
WHERE {
  SELECT DISTINCT ?pathway ?protein
  WHERE {
    ?pathway a bp:Pathway ;
             obo:RO_0000057 [
             a sio:SIO_010043 ;
             skos:closeMatch ?protein
           ] .
    FILTER(CONTAINS(STR(?protein), "http://purl.uniprot.org/uniprot/"))
  }
}
