# Endpoint: http://sparql.wikipathways.org/sparql
PREFIX wp: <http://vocabularies.wikipathways.org/wp#>

SELECT DISTINCT ?pathway_id ?doid_id
FROM <http://rdf.wikipathways.org/>
WHERE {
  ?pathway
    a wp:Pathway ;
    wp:diseaseOntologyTag ?doid .
  # Wikipathways uses https: for identifiers.org URIs...
  BIND (strafter(str(?pathway), "https://identifiers.org/wikipathways/") AS ?pathway_id)
  BIND (strafter(str(?doid), "http://purl.obolibrary.org/obo/DOID_") AS ?doid_id)
}
