# Endpoint: https://integbio.jp/rdf/bioportal/sparql
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>                                                                          
SELECT DISTINCT ?mondo_id ?do_id
FROM <http://rdf.integbio.jp/dataset/bioportal/mondo>
WHERE {
  ?mondo_uri
    oboInOwl:hasDbXref ?do ;
    oboInOwl:id ?mondo .
  FILTER (strstarts(?do, 'DOID:'))
  BIND (strafter(str(?do), 'DOID:') AS ?do_id)
  BIND (strafter(str(?mondo), 'MONDO:') AS ?mondo_id)
}
