link:
  file: sample.tsv
  forward: TIO_000106
  reverse: TIO_000107
update:
  frequency: Monthly
  method: curl -sS https://ddbj.nig.ac.jp/public/dblink/bioproject_umbrella-bioproject/bioproject_umbrella2bioproject.tsv | sed -e 's/\r//g'
