link:
  file: sample.tsv
  forward: TIO_000041
  reverse: TIO_000051
update:
  frequency: Monthly
  method: "wget https://ddbj.nig.ac.jp/public/rdf/dblink/bioproject_umbrella-bioproject/bioproject_umbrella2bioproject.tsv"
