link:
  file: sample.tsv
  forward: TIO_000106
  reverse: TIO_000107
update:
  frequency: Monthly
  method: curl -s https://ddbj.nig.ac.jp/public/rdf/dblink/bioproject_umbrella-bioproject/bioproject_umbrella2bioproject.tsv
