# Endpoint: https://integbio.jp/rdf/mirror/ebi/sparql
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#>
PREFIX bibo: <http://purl.org/ontology/bibo/>

SELECT DISTINCT ?chembl_id ?pubmed_id
FROM <http://rdf.ebi.ac.uk/dataset/chembl>
WHERE {
  ?molecule
    a cco:SmallMolecule ;
    cco:chemblId ?chembl ;
    cco:hasDocument/bibo:pmid ?pubmed .
  BIND (replace(?chembl, "CHEMBL", "") AS ?chembl_id)
  BIND (replace(str(?pubmed), "http://identifiers.org/pubmed/", "") AS ?pubmed_id) 
}
