link:
  forward: TIO_000031
  reverse: TIO_000030
  file: sample.tsv
update:
  frequency: freeze
  method: awk -F "\t" '$4&&$1!="ID"{split($4, b, "///"); for(k in b){print $1 "\t" b[k]}}' $TOGOID_ROOT/input/affy_probeset/GPL570.annot.tsv
