link:
  forward: TIO_000035
  reverse: TIO_000034
  file: sample.tsv
update:
  frequency: Monthly
  method: grep 'tag=MANE Select' $TOGOID_ROOT/input/mane/refseq_genomic.gff | awk -F '\t' '$3=="mRNA" {print $9}' | awk -F ';'  -v 'OFS=\t' '{split($1,b,"=rna-"); split($3,c,"GeneID:"); split(c[2],d,","); split(b[2],e,"-"); print d[1],e[1]}'
