# endopoint https://integbio.jp/rdf/bioportal/sparql
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT DISTINCT ?ordo_id ?omim_id
FROM <http://integbio.jp/rdf/mirror/bioportal/ordo>
WHERE {
  ?ordo_uri
    oboInOwl:hasDbXref ?omim.
  FILTER (strstarts(?omim,'OMIM:'))
  BIND (replace(str(?omim), 'OMIM:', '') AS ?omim_id)
  BIND (replace(str(?ordo_uri), 'http://www.orpha.net/ORDO/Orphanet_', '') AS ?ordo_id) 
}
