# Endpoint: https://rdfportal.org/ebi/sparql
# Graph: http://rdf.ebi.ac.uk/dataset/chebi

PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX chebi: <http://purl.obolibrary.org/obo/chebi/>

select DISTINCT   ?chebi_id ?chebi_inchikey
from <http://rdf.ebi.ac.uk/dataset/chebi>
where {
  ?chebi chebi:inchikey ?chebi_inchikey.
  BIND (strafter(str(?chebi), "CHEBI_") AS ?chebi_id)
} 
