# Endpoint: https://rdfportal.org/ebi/sparql
# Graph: http://rdf.ebi.ac.uk/dataset/chebi

PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX chemrof: <https://w3id.org/chemrof/>

SELECT DISTINCT ?chebi_id ?chebi_inchikey
FROM <http://rdf.ebi.ac.uk/dataset/chebi>
WHERE {
  ?chebi chemrof:inchi_key_string ?chebi_inchikey.
  BIND (strafter(str(?chebi), "CHEBI_") AS ?chebi_id)
}
