# Endpoint: https://integbio.jp/rdf/ebi/sparql
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#>

SELECT DISTINCT ?target ?go_id
FROM <http://rdf.ebi.ac.uk/dataset/chembl>
WHERE {
  ?mechanism a cco:Mechanism ;
    cco:hasTarget ?target ;
    cco:hasMolecule ?molecule .
  ?molecule cco:chemblId ?chembl_id .
  ?target cco:hasTargetComponent ?component .
  ?component cco:targetCmptXref ?go_uri .
  ?go_uri a cco:GoComponentRef .
  BIND (strafter(str(?go_uri), 'http://identifiers.org/obo.go/GO:') AS ?go_id)
}
