link:
  forward: TIO_000028
  reverse: TIO_000029
  file: sample.tsv
update:
  frequency: Bimonthly
  method: awk -F "\t" 'FNR>=2&&$46{gsub("\"","",$46); split($46,a,"|"); for(k in a)print substr($1,6) "\t" a[k]}' $TOGOID_ROOT/input/hgnc/hgnc_complete_set.txt
