# Endpoint: https://sparql.omabrowser.org/sparql/
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX orth: <http://purl.org/net/orth#>
PREFIX lscr: <http://purl.org/lscr#>

SELECT DISTINCT ?oma_protein_id ?ensg_id
WHERE {
  ?oma_protein orth:organism/obo:RO_0002162 <http://purl.uniprot.org/taxonomy/9606> .
  ?oma_protein sio:SIO_010079/lscr:xrefEnsemblGene ?ensg .

  BIND (replace(str(?oma_protein), 'https://omabrowser.org/oma/info/', '') AS ?oma_protein_id)
  BIND (replace(str(?ensg), 'http://rdf.ebi.ac.uk/resource/ensembl/', '') AS ?ensg_id)
}
