link:
  file: sample.tsv
  forward: TIO_000041
  reverse: TIO_000051
update:
  frequency: Monthly
  method: "wget https://ddbj.nig.ac.jp/public/rdf/dblink/trad_prefix-bioproject/trad_prefix2bioproject.tsv"
