- link:
    forward: TIO_000001
    reverse: TIO_000001
    file: sample1.tsv
    description: "This relationship includes the relations between Nando and Mondo terms that are linked within Nando using the `skos:exactMatch` or `skos:closeMatch` properties."
    description_ja: "Nando 内の記述で、`skos:exactMatch` または `skos:closeMatch` プロパティで関係づけられた Nando と Mondo のターム間の関係です。"
  update:
    frequency: Irregular
    method: sparql_csv2tsv.sh query_nearly_eq.rq https://nanbyodata.jp/sparql

- link:
    forward: TIO_000002
    reverse: TIO_000002
    file: sample2.tsv
    description: "This relationship only includes the relations between Nando and Mondo terms that are linked within Nando using the `skos:exactMatch` property."
    description_ja: "Nando 内の記述で、`skos:exactMatch` プロパティで関係づけられた Nando と Mondo のターム間の関係です。"
  update:
    frequency: Irregular
    method: sparql_csv2tsv.sh query_eq.rq https://nanbyodata.jp/sparql
