# Endpoint: https://togodx.dbcls.jp/human/sparql
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?nando_id ?mondo_id
FROM <http://rdf.integbio.jp/dataset/togosite/nando>
WHERE {
  ?nando 
    dcterms:identifier ?nandoid ;
    skos:closeMatch ?mondo .
  BIND (strafter(str(?nandoid), 'NANDO:') AS ?nando_id)
  BIND (strafter(str(?mondo), 'http://purl.obolibrary.org/obo/MONDO_') AS ?mondo_id)
}
