PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX taxon: <http://identifiers.org/taxonomy/>
PREFIX identifiers: <http://identifiers.org/>

SELECT DISTINCT ?ensg_id ?omim_id
WHERE {
  ?ensg obo:RO_0002162 taxon:9606 ;
        dc:identifier ?ensg_id ;
        rdfs:seeAlso ?omim .
  ?omim a identifiers:omim .
  BIND(STRAFTER(STR(?omim), "omim/") AS ?omim_id)
}
LIMIT 10
