link:
  forward: TIO_000001
  reverse: TIO_000001
  file: sample.tsv
update:
  frequency: Bimonthly
  method: awk -F "\t" 'FNR>=2&&$30{gsub("\"","",$30); split($30,a,"|"); for(k in a){if(a[k]~/^LRG_[0-9]+$/) print substr($1,6) "\t" a[k]}}' $TOGOID_ROOT/input/hgnc/hgnc_complete_set.tsv
