link:
  forward: TIO_000034
  reverse: TIO_000035
  file: sample.tsv
update:
  frequency: Weekly
  method: awk -F '\t' -v db=HGNC '$2==db{print $1 "_" $4 "\t" gensub("^HGNC:", "", "g", $3)}' $TOGOID_ROOT/input/rnacentral/id_mapping.tsv
