# Endpoint: https://integbio.jp/rdf/sib/sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rhea: <http://rdf.rhea-db.org/>

SELECT DISTINCT ?rhea_id ?reactome_id
FROM <http://rdf.integbio.jp/dataset/rhea>
WHERE {
  {
    ?rhea rdfs:subClassOf rhea:Reaction
  } UNION {
    ?rhea rdfs:subClassOf rhea:DirectionalReaction
  } UNION {
    ?rhea rdfs:subClassOf rhea:BidirectionalReaction
  }
  ?rhea rhea:accession ?rhea_acc ;
        rdfs:seeAlso ?reactome .
  FILTER (regex(?reactome, "reactome"))
  BIND (strbefore(strafter(str(?reactome), "reactome/"), ".") AS ?reactome_id)
  BIND (strafter(?rhea_acc, "RHEA:") AS ?rhea_id)
}
