# @endpoint https://lipidmaps.org/sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX chebi: <http://purl.obolibrary.org/obo/chebi/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?lipidmaps_id ?inchikey
WHERE {
  ?lipidmaps a owl:Class ;
             chebi:inchikey ?inchikey .
  BIND(STRAFTER(STR(?lipidmaps), "https://www.lipidmaps.org/rdf/") AS ?lipidmaps_id)
}
