link:
  forward: TIO_000010
  reverse: TIO_000011
  file: sample.tsv
update:
  frequency: Monthly
  method: awk -F "\t" '$6{split($6, a, "|"); for(k in a)print gensub(/^MGI:/, "", "g", a[k]) "\t" gensub(/^DOID:/, "", "g", $5)}' $TOGOID_ROOT/input/mgi_genotype/MGI_DiseaseGeneModel.rpt
