link:
  forward: TIO_000002
  reverse: TIO_000002
  file: sample.tsv
update:
  frequency: Monthly
  method: grep 'tag=MANE Select' $TOGOID_ROOT/input/mane/refseq_genomic.gff | awk -F '\t' '$3=="mRNA" {print $9}' | awk -F';' '{split($1,b,"=rna-"); split($3,c,"Ensembl:"); split(c[2],d,"."); split(b[2],e,"."); print e[1], "\t", d[1]}'
