link:
  forward: TIO_000002
  reverse: TIO_000002
  file: sample.tsv
update:
  frequency: Monthly
  method: grep 'tag=MANE Select' $TOGOID_ROOT/input/mane/refseq_genomic.gff | awk -F '\t' '$3=="mRNA" {print $9}' | awk -F ';' -v 'OFS=\t' '{split($1,b,"=rna-"); split($3,c,"Ensembl:"); split(b[2],d,"-"); split(c[2],e,","); print d[1],e[1]}'
