# Endpoint: https://rdfportal.org/sib/sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rhea: <http://rdf.rhea-db.org/>
PREFIX pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
SELECT DISTINCT ?rhea_id ?pubmed_id
FROM <http://rdfportal.org/dataset/rhea>
WHERE {
  VALUES ?reaction {rhea:Reaction rhea:DirectionalReaction rhea:BidirectionalReaction }
  ?rhea rdfs:subClassOf ?reaction ;
        rhea:citation ?pubmed .
  BIND (STRAFTER(STR(?rhea), "rhea-db.org/") AS ?rhea_id)
  BIND (STRAFTER(STR(?pubmed), "pubmed/") AS ?pubmed_id)
}
