link:
  file: sample.tsv
  forward: TIO_000095
  reverse: TIO_000094
update:
  frequency: Monthly
  method: curl -sS https://ddbj.nig.ac.jp/public/rdf/dblink/biosample-bioproject/biosample2bioproject.tsv
