PREFIX mo: <http://med2rdf/ontology/medgen#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?medgen_id ?orphanet_id
FROM <http://rdf.integbio.jp/dataset/togosite/medgen>
WHERE {
  ?medgen_uri
    dct:identifier ?medgen_id ;
    mo:mgconso ?mgconso .
  ?mgconso
    dct:source mo:ORDO ;
    rdfs:seeAlso ?orphanet .
  BIND (strafter(str(?orphanet), 'http://www.orpha.net/ORDO/Orphanet_') AS ?orphanet_id)
}
