# pubchem_pathway-pubchem_compound
PREFIX bp:  <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?path_id ?cid
FROM <http://rdf.ncbi.nlm.nih.gov/pubchem/pathway>
WHERE {
    ?pathway a bp:Pathway;
      obo:RO_0000057 ?participant.
    FILTER(STRSTARTS(STR(?participant), "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID"))
    BIND(STRAFTER(STR(?pathway), "http://rdf.ncbi.nlm.nih.gov/pubchem/pathway/PWID") AS ?path_id)
    BIND(STRAFTER(STR(?participant), "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID") AS ?cid)
}
