# https://integbio.jp/rdf/ebi/sparql
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#> 
PREFIX cheminf: <http://semanticscience.org/resource/>
SELECT distinct ?chemble_id  ?inchikey
FROM <http://rdf.ebi.ac.uk/dataset/chembl>
where {
 ?chembl_molecule a cco:SmallMolecule ;
                  cco:chemblId ?chemble_id ;
                  cheminf:SIO_000008 ?inchi_inchikey .
?inchi_inchikey a cheminf:CHEMINF_000059;
                cheminf:SIO_000300 ?inchikey .
}