PREFIX sio: <http://semanticscience.org/resource/>

SELECT (substr(str(?cid), 49) as ?pubchem_id) ?chebi_id {
SELECT DISTINCT ?cid ?chebi_id
FROM <http://rdf.integbio.jp/dataset/pubchem>
WHERE {
  [] sio:is-attribute-of ?cid ;
     a sio:CHEMINF_000407 ; # ChEBI identifier
     sio:has-value ?chebi .
  BIND (substr(?chebi, 7) AS ?chebi_id)
}
}
