link:
  forward: TIO_000034
  reverse: TIO_000035
  file: sample.tsv
update:
  frequency: Bimonthly
  method: awk -F "\t" '$1&&$8{split($8, b, ","); for(k in b){if(!a[$1, b[k]]++)print $1 "\t" b[k]}}' $TOGOID_ROOT/input/refseq_rna/refseq_rna_summary.tsv
