PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oboinowl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT ?cl_id ?fma_id
FROM <http://purl.obolibrary.org/obo/merged/CL>
WHERE {
  ?cl oboinowl:hasDbXref ?fma .
  FILTER(STRSTARTS(STR(?cl), "http://purl.obolibrary.org/obo/CL_"))
  FILTER(STRSTARTS(STR(?fma), "FMA:"))
  BIND(STRAFTER(STR(?cl), "http://purl.obolibrary.org/obo/CL_") AS ?cl_id)
  BIND(STRAFTER(STR(?fma), "FMA:") AS ?fma_id)
}
