PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX source: <http://rdf.ncbi.nlm.nih.gov/pubchem/source/>
PREFIX cheminf: <http://semanticscience.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?pubchem_id ?glytoucan_id {
  [ dcterms:source source:ID11830 ;
    rdfs:seeAlso ?glytoucan ;
    cheminf:CHEMINF_000477 ?pubchem ] .
  BIND(STRAFTER(STR(?pubchem), "compound/CID") AS ?pubchem_id)
  FILTER (STRSTARTS(STR(?glytoucan), "http://identifiers.org/glytoucan:"))
  BIND(STRAFTER(STR(?glytoucan), "http://identifiers.org/glytoucan:") AS ?glytoucan_id)
}
