# Endpoint: https://rdfportal.org/ebi/sparql
PREFIX so: <http://purl.obolibrary.org/obo/so#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?tax_id
WHERE {
  [] so:transcribed_from ?ensg .
  ?ensg obo:RO_0002162 ?taxon .  # in-taxon
  ?taxon dcterms:identifier ?tax_id .
}
