# Endpoint: https://integbio.jp/rdf/ebi/sparql
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

# GRAPH varies e.g., http://rdf.ebi.ac.uk/dataset/ensembl/102/homo_sapiens for tax_id 9606
SELECT DISTINCT ?tax_id
WHERE {
  ?ensg obo:RO_0002162 ?taxon .  # in-taxon
  ?taxon dc:identifier ?tax_id .
  # FILTER (strstarts(str(?taxon), "http://identifiers.org/taxonomy/"))
}
