## endpoint https://integbio.jp/rdf/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX biolink: <https://w3id.org/biolink/vocab/>
PREFIX ordo: <http://www.orpha.net/ORDO/>
PREFIX ncbigene: <http://identifiers.org/ncbigene/>
 
SELECT DISTINCT ?hp_id ?ncbigene_id
FROM <http://rdf.integbio.jp/dataset/monarch>
WHERE { 
  ?ncbigene
   biolink:has_phenotype ?hp.
   FILTER (strstarts(str(?ncbigene),'http://identifiers.org/ncbigene/'))
   BIND (strafter(str(?ncbigene), 'http://identifiers.org/ncbigene/') AS ?ncbigene_id)
   BIND (strafter(str(?hp), 'http://purl.obolibrary.org/obo/HP_') AS ?hp_id)
 }