# Endpoint: https://integbio.jp/rdf/ebi/sparql
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#>

SELECT DISTINCT ?chembl_id ?drugbank_id
FROM <http://rdf.ebi.ac.uk/dataset/chembl>
WHERE{
  ?molecule
    a cco:SmallMolecule ;
    cco:chemblId ?chembl ;
    cco:moleculeXref ?drugbank .
  FILTER (contains(str(?drugbank), "drugbank"))
  BIND (replace(?chembl, "CHEMBL", "") AS ?chembl_id)
  BIND (replace(str(?drugbank), "http://www.drugbank.ca/drugs/", "") AS ?drugbank_id)
}
