# Endpoint: https://integbio.jp/rdf/mirror/ebi/sparql
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#>
SELECT ?chembl_id ?drugbank_id
FROM <http://rdf.ebi.ac.uk/dataset/chembl>
WHERE{
  ?molecule  a cco:SmallMolecule ;
    cco:moleculeXref ?drugbank .
  FILTER (contains(str(?drugbank), "drugbank"))
  BIND (replace(str(?molecule), "http://rdf.ebi.ac.uk/resource/chembl/molecule/CHEMBL", "") AS ?chembl_id)
  BIND (replace(str(?drugbank), "http://www.drugbank.ca/drugs/", "") AS ?drugbank_id)
}
