# Endpoint: https://integbio.jp/rdf/ebi/sparql
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#>

SELECT DISTINCT ?chembl_id ?xref_id
FROM <http://rdf.ebi.ac.uk/dataset/chembl>
WHERE {
  ?mechanism a cco:Mechanism ;
    cco:hasTarget ?target ;
    cco:hasMolecule ?molecule .
  ?molecule cco:chemblId ?chembl_id .
  ?target cco:hasTargetComponent ?component .
  ?component cco:targetCmptXref ?xref_uri .
  ?xref_uri a cco:InterproRef .
  BIND (strafter(str(?xref_uri), 'http://identifiers.org/interpro/') AS ?xref_id)
}
