# Endpoint: https://togovar-dev.biosciencedbc.jp/sparql
PREFIX tgvo: <http://togovar.biosciencedbc.jp/vocabulary/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cvo: <http://purl.jp/bio/10/clinvar/>

SELECT DISTINCT ?tgv_id ?vcv
WHERE {
  GRAPH <http://togovar.biosciencedbc.jp/variation>{
     ?variation dct:identifier ?tgv_id.
  }

  GRAPH <http://togovar.biosciencedbc.jp/variation/annotation/clinvar>{
     ?variation tgvo:condition / rdfs:seeAlso ?clinvar .
  }

  BIND(REPLACE(STR(?clinvar), "http://ncbi.nlm.nih.gov/clinvar/variation/", "") AS ?vcv)
}
