link:
  forward: TIO_000037
  reverse: TIO_000036
  file: sample.tsv
update:
  frequency: twoTimesAYear
  method: sparql_taxon.rb query.rq https://sparql.omabrowser.org/sparql/ $TOGOID_ROOT/input/oma_protein/oma_ensembl_vertebrate_taxonomy.txt
