link:
  forward: TIO_000025
  reverse: TIO_000024
  file: sample.tsv
update:
  frequency: Monthly
  method: awk -F "\t" '{split($7, a, " "); for(k in a){print gensub(/^MGI:/, "", "g", $1) "\t" a[k]}}' $TOGOID_ROOT/input/mgi_gene/MRK_SwissProt_TrEMBL.rpt
