link:
  forward: TIO_000017
  reverse: TIO_000017
  file: sample.tsv
update:
  frequency: Bimonthly
  method: awk -F "\t" 'FNR>=2&&$29{gsub("\"","",$29); split($29,a,"|"); for(k in a)print substr($1,6) "\t" substr(a[k],5)}' $TOGOID_ROOT/input/hgnc/hgnc_complete_set.tsv
