link:
  forward: TIO_000002
  reverse: TIO_000002
  file: sample.tsv
update:
  frequency: Weekly
  method: awk -F "\t" '$2=="SWISSLIPIDS_ID"{print $1 "\t" gensub(/^SLM:/, "", "g", $3)}' $TOGOID_ROOT/input/lipidmaps/lipidmaps.tsv
