# Endpoint: https://rdfportal.org/ebi/sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX taxon: <http://identifiers.org/taxonomy/>
PREFIX so: <http://purl.obolibrary.org/obo/so#>

SELECT DISTINCT ?ensg_id ?uniprot_id
FROM <http://rdfportal.org/dataset/ensembl>
WHERE {
  VALUES ?taxon { taxon:{{taxon}} }
  ?ensg obo:RO_0002162 ?taxon ;
        dcterms:identifier ?ensg_id .
  ?enst so:transcribed_from ?ensg ;
        so:translates_to / rdfs:seeAlso ?uniprot .
  FILTER (STRSTARTS (STR(?uniprot), "http://purl.uniprot.org/uniprot/"))
  BIND(STRAFTER(STR(?uniprot), "uniprot/") AS ?uniprot_id)
}
