# Endpoint: https://rdfportal.org/ebi/sparql
PREFIX biopax: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?reactome_id ?go_id
FROM <http://rdf.ebi.ac.uk/dataset/reactome>
WHERE {
  ?path biopax:xref [
    biopax:db 'Reactome'^^xsd:string ;
    biopax:id ?reactome_id
  ] ;
  biopax:xref [
    biopax:db 'GENE ONTOLOGY'^^xsd:string ;
    biopax:id ?go
  ] ;
  a biopax:Pathway .
  BIND (strafter(?go, "GO:") AS ?go_id)
}
