link:
  forward: TIO_000077
  reverse: TIO_000076
  file: sample.tsv
update:
  frequency: Monthly
  method: awk -F '\t' '{gsub(/-[0-9]+$/, "", $1);print $2 "\t" $1}' $TOGOID_ROOT/input/reactome/UniProt2ReactomeReactions.txt
