# Endpoint: https://integbio.jp/rdf/bioportal/sparql
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT ?do_id ?ncit_id
FROM <http://rdf.integbio.jp/dataset/bioportal/doid>
WHERE {
  ?do_uri
    oboInOwl:hasDbXref ?ncit ;
    oboInOwl:id ?do .
  FILTER (strstarts(?ncit,'NCI:'))
  BIND (strafter(str(?ncit), 'NCI:') AS ?ncit_id)
  BIND (strafter(str(?do), 'DOID:') AS ?do_id)
}
