PREFIX bp: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT  distinct ?path_id ?protein
WHERE {
 ?pathway a bp:Pathway ;
     obo:RO_0000057/skos:closeMatch ?participant.

FILTER contains (str(?participant), "NP_") 
BIND (strafter(str(?pathway), "http://rdf.ncbi.nlm.nih.gov/pubchem/pathway/PWID") AS ?path_id)
BIND (strafter(str(?participant), "https://www.ncbi.nlm.nih.gov/protein/") AS ?protein)
}