link:
  forward: TIO_000024
  reverse: TIO_000025
  file: sample.tsv
update:
  frequency: twoTimesAYear
  method: sparql_taxon.rb query.rq https://sparql.omabrowser.org/sparql/ $TOGOID_ROOT/input/oma/taxonomy.txt
