link:
  forward: TIO_000024
  reverse: TIO_000025
  file: sample.tsv
update:
  frequency: twoTimesAYear
  method: awk -F "\t" '$4=="Ensembl" && $5~/Ensembl (Vertebrates )?[0-9]+;/ && $1!="YEAST"{print $2}' $TOGOID_ROOT/input/oma/oma-species.txt > taxonomy.txt
    && sparql_taxon.rb query.rq https://sparql.omabrowser.org/sparql/ taxonomy.txt

