# Endpoint: https://sparql.omabrowser.org/sparql/
PREFIX orth: <http://purl.org/net/orth#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX uptax: <http://purl.uniprot.org/taxonomy/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX lscr: <http://purl.org/lscr#>

SELECT DISTINCT ?oma_protein_id ?ensg_id
FROM <http://omabrowser.org/graph>
WHERE {
  VALUES ?taxon { uptax:{{taxon}} }
  ?oma_protein a orth:Protein ;
               orth:organism/obo:RO_0002162 ?taxon ;
               sio:SIO_010079/lscr:xrefEnsemblGene ?ensg .
  BIND (strafter(str(?oma_protein), 'https://omabrowser.org/oma/info/') AS ?oma_protein_id)
  BIND (strafter(str(?ensg), 'http://rdf.ebi.ac.uk/resource/ensembl/') AS ?ensg_id)
}
