PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX pubchemv: <http://rdf.ncbi.nlm.nih.gov/pubchem/vocabulary#>
PREFIX bp: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

select distinct (substr(str(?cid),49) AS ?_cid) (substr(str(?up),33) AS ?_up)
#from <http://rdf.integbio.jp/dataset/pubchem>
where {
  ?cid obo:has-role pubchemv:FDAApprovedDrugs ;
       obo:BFO_0000056 [
         a bp:Pathway ;
         ^obo:BFO_0000056 [
           a bp:Protein ;
           skos:closeMatch ?up ]].
  filter contains(str(?up),"uniprot")
}
