# https://integbio.jp/rdf/pubchem/sparql
# pubchem_pathway-pubchem_protein

PREFIX bp:	<http://www.biopax.org/release/biopax-level3.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT  distinct?path_id ?protein_id
 WHERE {
   ?pathway a bp:Pathway ;
     obo:RO_0000057 ?participant .
FILTER contains (str(?participant), "protein") 
BIND (strafter(str(?pathway), "http://rdf.ncbi.nlm.nih.gov/pubchem/pathway/PWID") AS ?path_id)
BIND (substr(str(?participant), 49) AS ?protein_id)
}