# https://integbio.jp/rdf/sparql
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?nando_id ?mondo_id
FROM <http://nanbyodata.jp/ontology/nando>
WHERE {
  ?nando 
    dcterms:identifier ?nando_id ;
    skos:closeMatch ?mondo .
  BIND (replace(str(?mondo), 'http://purl.obolibrary.org/obo/MONDO_', '') AS ?mondo_id) 
  }
