link:
  forward: TIO_000116
  reverse: TIO_000117
  file: sample.tsv
update:
  frequency: Monthly
  method: awk -F "\t" '{split($3, a, "|"); for(k in a)print gensub(/^MGI:/, "", "g", $8) "\t" gensub(/^MGI:/, "", "g", a[k])}'  $TOGOID_ROOT/input/mgi_genotype/MGI_GenePheno.rpt | sort | uniq
