link:
  forward: TIO_000032
  reverse: TIO_000033
  file: sample.tsv
update:
  frequency: Bimonthly
  method: awk -F "\t" 'FNR>=2&&$27{gsub("\"","",$27); split($27,a,"|"); for(k in a)print substr($1,6) "\t" a[k]}' $TOGOID_ROOT/input/hgnc/hgnc_complete_set.txt
