link:
  forward: TIO_000101
  reverse: TIO_000100
  file: sample.tsv
update:
  frequency: Irregular
  method: awk -F "\t" '$1~/^ORPHA/&&$11=="P"&&$3!="NOT"{print substr($4,4) "\t" substr($1,7)}' $TOGOID_ROOT/input/hp_phenotype/phenotype.hpoa
