link:
  file: assembly_genome2bs.tsv
  forward: TIO_000042
  reverse: TIO_000052
update:
  frequency: Monthly
  method: "wget https://ddbj.nig.ac.jp/public/rdf/dblink/assembly_genome-bs/assembly_genome2bs.tsv"
