PREFIX compound: <http://rdf.ncbi.nlm.nih.gov/pubchem/compound/>
PREFIX inchikey: <http://rdf.ncbi.nlm.nih.gov/pubchem/inchikey/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX cheminf: <http://semanticscience.org/resource/>

SELECT (substr(str(?cid),46) as ?cid_str) (substr(str(?inchikey),46) as ?inchikey_str)
FROM <http://rdf.ncbi.nlm.nih.gov/pubchem/inchikey>
WHERE {
  ?inchikey sio:is-attribute-of ?cid ;
            a cheminf:CHEMINF_000399 .
}
