# endopoint https://integbio.jp/rdf/bioportal/sparql
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT DISTINCT ?ordo_id ?meddra_id
FROM <http://integbio.jp/rdf/mirror/bioportal/ordo>
WHERE {
  ?ordo_uri oboInOwl:hasDbXref ?meddra.
  FILTER (strstarts(?meddra,'MedDRA:'))
  BIND (replace(str(?meddra), 'MedDRA:', "") AS ?meddra_id)
  BIND (replace(str(?ordo_uri), 'http://www.orpha.net/ORDO/Orphanet_', '') AS ?ordo_id) 
}
