# Endpoint: http://sparql.wikipathways.org/sparql
# 20210215 moriya
# 20210311 ikeda edited
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wp: <http://vocabularies.wikipathways.org/wp#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?pathway_id ?chebi_id
WHERE {
  ?pathway a wp:Pathway .
  ?chebi dct:isPartOf* ?pathway ;
           a wp:Metabolite ;
           dc:source 'ChEBI'^^xsd:string .
  BIND(REPLACE(STR(?pathway), "https://identifiers.org/wikipathways/", "") AS ?pathway_id)
  BIND(REPLACE(STR(?chebi), "https://identifiers.org/chebi/CHEBI:", "") AS ?chebi_id)
}
