link:
  forward: TIO_000015
  reverse: TIO_000013
  file: sample.tsv
update:
  frequency: Bimonthly
  method: cut -f 1-2 $TOGOID_ROOT/input/interpro/protein2ipr.dat | sort -c && awk -F "\t" '{print $2 "\t" $1}' $TOGOID_ROOT/input/interpro/protein2ipr.dat | uniq
