# Endpoint: https://integbio.jp/rdf/pdb/sparql
PREFIX pdbo: <http://rdf.wwpdb.org/schema/pdbx-v50.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?pdb_id ?target_id
FROM <http://rdf.integbio.jp/dataset/pdbj>
WHERE {
  ?pdb pdbo:has_entityCategory ?ecats .
  ?ecats pdbo:has_entity ?entity .
  ?entity pdbo:referenced_by_struct_asym/pdbo:referenced_by_pdbx_sifts_xref_db_segments/rdfs:seeAlso ?target .
  FILTER (regex(?target ,'go/GO'))
  BIND (strafter(str(?pdb), "http://rdf.wwpdb.org/pdb/") AS ?pdb_id)
  BIND (strafter(str(?target), "http://identifiers.org/go/GO:") AS ?target_id)
}
