link:
  forward: TIO_000082
  reverse: TIO_000083
  file: sample.tsv
update:
  frequency: Quarterly
  method: awk 'BEGIN{RS="\n//\n";FS="\n"}{n=0; for(i=1;i<=NF;i++){if($i~/^AC/){ac=substr($i,11)}if($i~/^DI   NCIt;/){split($i,b,"; "); n++; ncit[n]=b[2]}}for(i=1;i<=n;i++){print ac "\t" ncit[i]} delete ncit}' $TOGOID_ROOT/input/cellosaurus/cellosaurus.txt
