link:
  file: sample.tsv
  forward: TIO_000094
  reverse: TIO_000095
update:
  frequency: Monthly
  method: curl -sS https://ddbj.nig.ac.jp/public/dblink/bioproject-biosample/bioproject2biosample.tsv
