link:
  file: sample.tsv
  forward: TIO_000094
  reverse: TIO_000095
update:
  frequency: Monthly
  method: awk -F "\t" 'FNR==1{fn++} fn==1{b[$1,$2]=1; print $1 "\t" $2} fn==2&&$2=="ID"{a[$3]=$1} fn==3&&$2=="BioProject ID"&&a[$3]&&!b[a[$3],$1]{print a[$3] "\t" $1}' $TOGOID_ROOT/input/bioproject/bioproject2biosample.tsv $TOGOID_ROOT/input/bioproject/bioproject.tsv $TOGOID_ROOT/input/biosample/biosample_set.tsv
