# Endpoint: https://rdfportal.org/bioportal/sparql
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
SELECT DISTINCT ?do_id ?mesh_id
FROM <http://rdfportal.org/dataset/bioportal/doid>
WHERE {
  ?do_uri 
    oboInOwl:hasDbXref ?mesh ;
    oboInOwl:hasOBONamespace "disease_ontology" ;
    oboInOwl:id ?do .
  FILTER (strstarts(?mesh,'MESH:'))
  BIND (strafter(str(?mesh), 'MESH:') AS ?mesh_id)
  BIND (strafter(str(?do), 'DOID:') AS ?do_id)
}
