# Endpoint: https://integbio.jp/rdf/pubchem/sparql
PREFIX sio: <http://semanticscience.org/resource/>

SELECT DISTINCT ?pubchem_id ?chembl_id
FROM <http://rdf.integbio.jp/dataset/pubchem>
WHERE {
  [] sio:is-attribute-of ?cid ;
     a sio:CHEMINF_000412 ;
     sio:has-value ?chembl .
  BIND (strafter(str(?cid), "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/") AS ?pubchem_id)
  BIND (ucase(str(?chembl)) AS ?chembl_id)
}
