# Endpoint: https://integbio.jp/rdf/pubchem/sparql
PREFIX sio: <http://semanticscience.org/resource/>

SELECT DISTINCT ?pubchem_id ?chembl_id
WHERE {
  [ sio:is-attribute-of ?cid ;
    a sio:CHEMINF_000412 ;
    sio:has-value ?chembl ] .
  BIND (substr(str(?cid),49) AS ?pubchem_id)
  BIND (concat("CHEMBL", (substr(str(?chembl),7))) AS ?chembl_id)
}
