PREFIX dct: <http://purl.org/dc/terms/>
PREFIX mo: <http://med2rdf/ontology/medgen#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?medgen_id ?omim_id 
FROM <http://rdf.integbio.jp/dataset/togosite/medgen>
WHERE {
  ?medgen_uri
    dct:identifier ?medgen_id ;
    mo:mgconso ?mgconso .
  ?mgconso
    dct:source mo:OMIM ;
    rdfs:seeAlso ?omim .
  ?omim mo:mim_type ?type.
  FILTER(REGEX(?type,'phenotype'))
  BIND (replace(str(?omim), 'http://identifiers.org/mim/', '') AS ?omim_id)
}
