# Endpoint: https://rdfportal.org/ebi/sparql
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX taxon: <http://identifiers.org/taxonomy/>

SELECT DISTINCT ?ensg_id ?ncbigene_id
FROM <http://rdfportal.org/dataset/ensembl>
WHERE {
  VALUES ?taxon { taxon:{{taxon}} }
  ?ensg obo:RO_0002162 ?taxon ;
        rdfs:seeAlso ?ncbigene ;
        dcterms:identifier ?ensg_id .
  FILTER (STRSTARTS (STR(?ncbigene), "http://identifiers.org/ncbigene/"))
  BIND (STRAFTER(STR(?ncbigene), "ncbigene/") AS ?ncbigene_id)
}
