# Endpoint: https://integbio.jp/rdf/ebi/sparql
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX taxon: <http://identifiers.org/taxonomy/>
PREFIX ido: <http://identifiers.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# GRAPH varies e.g., http://rdf.ebi.ac.uk/dataset/ensembl/102/homo_sapiens for tax_id 9606
SELECT DISTINCT ?ensg_id ?ncbigene_id
WHERE {
  VALUES ?taxon { taxon:{{taxon}} }
  ?ensg obo:RO_0002162 ?taxon ;
        rdfs:seeAlso ?ncbigene ;
        dc:identifier ?ensg_id .
  ?ncbigene a ido:ncbigene .
  BIND (strafter(str(?ncbigene), "ncbigene/") AS ?ncbigene_id)
}
