# Endpoint: https://rdfportal.org/pubchem/sparql

PREFIX sio: <http://semanticscience.org/resource/>
PREFIX cheminf: <http://semanticscience.org/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX pubchemv: <http://rdf.ncbi.nlm.nih.gov/pubchem/vocabulary#>

SELECT DISTINCT ?pubchem_id ?drugbank_id
FROM <http://rdf.ncbi.nlm.nih.gov/pubchem/synonym>
{
  [ a cheminf:CHEMINF_000406 ;
    sio:SIO_000300 ?drugbank_id ;
    sio:SIO_000011 ?cid ] .
    BIND (STRAFTER(STR(?cid), "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID") AS ?pubchem_id)
}
