# Endpoint: https://integbio.jp/rdf/pubchem/sparql

PREFIX sio: <http://semanticscience.org/resource/>
PREFIX cheminf: <http://semanticscience.org/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX pubchemv: <http://rdf.ncbi.nlm.nih.gov/pubchem/vocabulary#>

select distinct ?pubchem_id ?drugbunk_id
from <http://rdf.integbio.jp/dataset/pubchem>
{
  [ a cheminf:CHEMINF_000406 ;
    cheminf:has-value ?dbid ;
    sio:is-attribute-of ?cid ] .
    BIND (ucase(str(?dbid)) as  ?drugbunk_id)
    BIND (strafter(str(?cid), "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID") AS ?pubchem_id)
} 
