# https://integbio.jp/rdf/pubchem/sparql
# pubchem_gene-ensembl_gene

PREFIX bp:	<http://www.biopax.org/release/biopax-level3.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT  distinct ?pubchem_gene ?ensg
WHERE {
 ?pathway a bp:Pathway ;
     obo:RO_0000057 ?participant.
 ?participant skos:closeMatch ?gene .
FILTER contains (str(?gene), "ENSG") 
BIND (strafter(str(?participant), "http://rdf.ncbi.nlm.nih.gov/pubchem/gene/GID") AS ?pubchem_gene)
BIND (strafter(str(?gene), "http://rdf.ebi.ac.uk/resource/ensembl/") AS ?ensg)
}