link:
  forward: TIO_000024
  reverse: TIO_000025
  file: sample.tsv
update:
  frequency: twoTimesAYear
  method: zcat $TOGOID_ROOT/input/oma_protein/oma-entrez.txt.gz | awk -F "\t" '/^[^#]/&&$2~/^[0-9; ]+$/{split($2, a, "; "); for(k in a){if(!b[a[k]]++)print $1 "\t" a[k]}; delete b}'
