# Endpoint: https://rdfportal.org/bioportal/sparql
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?ordo_id ?omim_id
FROM <http://rdf.integbio.jp/dataset/bioportal/ordo>
WHERE {
  ?ordo rdfs:subClassOf+ <http://www.orpha.net/ORDO/Orphanet_C001> ;
        oboInOwl:hasDbXref ?omim .

  FILTER (STRSTARTS(?omim, 'OMIM:'))
  BIND (STRAFTER(STR(?ordo), 'http://www.orpha.net/ORDO/Orphanet_') AS ?ordo_id)
  BIND (STRAFTER(?omim, 'OMIM:') AS ?omim_id)
}
