# endopoint https://integbio.jp/rdf/bioportal/sparql
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT ?ordo_id ?mesh_id
FROM <http://rdf.integbio.jp/dataset/bioportal/ordo>
WHERE {
  ?ordo_uri oboInOwl:hasDbXref ?mesh.
  FILTER (strstarts(?mesh,'MeSH:'))
  BIND (strafter(str(?mesh), 'MeSH:') AS ?mesh_id)
  BIND (strafter(str(?ordo_uri), 'http://www.orpha.net/ORDO/Orphanet_') AS ?ordo_id)
}
