# Endpoint: https://integbio.jp/rdf/sparql
PREFIX pdbr: <https://rdf.wwpdb.org/pdb/>
PREFIX pdbo: <https://rdf.wwpdb.org/schema/pdbx-v50.owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?pdb_id ?target_id
 FROM <http://rdf.integbio.jp/dataset/pdbj>
WHERE {
    ?pdb          pdbo:has_entityCategory ?entity_category .
    ?entity_category pdbo:has_entity         ?entity .
    ?entity          pdbo:referenced_by_struct_ref ?struct_ref .
    ?struct_ref      pdbo:link_to_uniprot    ?target .
    BIND(REPLACE(STR(?pdb), pdbr:, "") AS ?pdb_id)
    BIND(REPLACE(STR(?target), "http://purl.uniprot.org/uniprot/", "") AS ?target_id)
}
