PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX bp: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sio: <http://semanticscience.org/resource/>

select (substr(str(?cid),49) as ?compound_id) (substr(str(?ensg),39) as ?ensg_id){
select distinct ?cid ?ensg
where {
  [ sio:CHEMINF_000477 ?cid ] . # ?cid を PubChem compound IDに絞るための条件
  ?cid ^obo:RO_0000057 [
    a bp:Pathway ;
    obo:RO_0000057 [
      a bp:Gene ;
      skos:closeMatch ?ensg
      ]].
#  BIND (strafter(str(?ensg), "http://rdf.ebi.ac.uk/resource/ensembl/") AS ?ensg_id)
#  BIND (strafter(str(?cid), "http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID") AS ?pubchem_id)
}
}
