link:
  forward: TIO_000010
  reverse: TIO_000011
  file: sample.tsv
update:
  frequency: Monthly
  method: awk -F "\t" '$6~/^MP:/&&!a[$1, $6]++{print gensub(/^MGI:/,"","g",$1) "\t" gensub(/^MP:/,"","g",$6)}' $TOGOID_ROOT/input/mgi_genotype/mousemine_genotype.tsv
