link:
  forward: TIO_000001
  reverse: TIO_000001
  file: sample.tsv
update:
  frequency: Weekly
  method: awk -F '\t' '$6~/MGI:MGI:/{split($6,a,"|");for(k in a){if(a[k]~/^MGI:/)print $2 "\t" substr(a[k],9)}}' $TOGOID_ROOT/input/ncbigene/gene_info
